### ISSUE TITLE
哥，考公后博客打不开了

### ISSUE THREAD

**Issue by fengzhao** [zhangferry/AIDailyNews#22]
https://zhangferry.com/2023/08/31/17_interview_anyu_kaogong/

**Comment by zhangferry** [comment]
> https://zhangferry.com/2023/08/31/17_interview_anyu_kaogong/
站点有点问题还没时间修，可以看公众号链接：https://mp.weixin.qq.com/s?__biz=MzU2MDQzMjM3Ng==&mid=2247490382&idx=1&sn=cc8cb05714d5bd49bfc23fc0594143ea

**Comment by fengzhao** [comment]
收到
